### Найти A + B:

$A =\begin{pmatrix}
1 & 3 & 0\\
2 & -4 & 3\\
5 & 6 & 9
\end{pmatrix}$

$B =\begin{pmatrix}
10 & 6 & -2\\
0 & 7 & 4\\
-1 & 2 & 0
\end{pmatrix}$


$C = A + B = \begin{pmatrix}
{1+10} & {3+6} & {0+(-2)}\\
{2+0} & {-4+7} & {3+4}\\
{5+(-1)} & {6+2} & {9+0}
\end{pmatrix} 
=\begin{pmatrix}
{11} & {9} & {-2}\\
{2} & {3} & {7}\\
{4} & {8} & {9}
\end{pmatrix}$

In [2]:
import numpy as np

In [4]:
A=np.matrix([[1,3,0],[2,-4,3],[5,6,9]])
A

matrix([[ 1,  3,  0],
        [ 2, -4,  3],
        [ 5,  6,  9]])

In [5]:
B=np.matrix([[10,6,-2],[0,7,4],[-1,2,0]])
B

matrix([[10,  6, -2],
        [ 0,  7,  4],
        [-1,  2,  0]])

In [6]:
C=A+B
C

matrix([[11,  9, -2],
        [ 2,  3,  7],
        [ 4,  8,  9]])

### Найти A * B:

$A =\begin{pmatrix}
2 & 8\\
3 & 4
\end{pmatrix}$

$B =\begin{pmatrix}
1 & 0\\
4 & 9
\end{pmatrix}$


$C = A * B = \begin{pmatrix}
{2*1+8*4} & {2*0+8*9}\\
{3*1+4*4} & {3*0+4*9}
\end{pmatrix} 
=\begin{pmatrix}
{34} & {72}\\
{19} & {36}
\end{pmatrix}$

In [8]:
A=np.matrix([[2,8],[3,4]])
A

matrix([[2, 8],
        [3, 4]])

In [9]:
B=np.matrix([[1,0],[4,9]])
B

matrix([[1, 0],
        [4, 9]])

In [10]:
C=A*B
C

matrix([[34, 72],
        [19, 36]])

### Вычислить определители:

$det\begin{pmatrix}
3 & 7\\
6 & 9
\end{pmatrix}=3*9-7*6=-15$

In [11]:
A=np.matrix([[3,7],[6,9]])
A

matrix([[3, 7],
        [6, 9]])

In [12]:
np.linalg.det(A)

-15.0

$det\begin{pmatrix}
4 & 1 & 9\\
3 & 2 & 0\\
8 & 7 & 5
\end{pmatrix}=4*2*5 + 1*0*8 + 9*3*7 - 9*2*8 - 4*7*0 - 1*3*5 = 40 + 0 + 189 - 144 - 0 - 15 = 70$

In [13]:
A=np.matrix([[4,1,9],[3,2,0],[8,7,5]])
A

matrix([[4, 1, 9],
        [3, 2, 0],
        [8, 7, 5]])

In [14]:
np.linalg.det(A)

69.99999999999996