### Pandas

* Скачайте любой табличный датасет (можете использовать тот же, что и в дз к занятию "Знакомство с библиотеками"), например, с https://www.kaggle.com/datasets
* Проведите поноценный EDA 
    * "погрузитесь" в данные
    * составьте описание измерений из датасета
    * очистите данные, если это необходимо
    * попробуйте создать дополнительные переменные, которые могут помочь лучше понять данные

In [1]:
import pandas as pd


In [2]:
df = pd.read_csv('new-used-cars-dataset.csv')
df.head()

Car Names    Mileages  Ratings          Reviews  \
0               2019 Honda Accord Sport     Mileage      3.7      (3 reviews)   
1  2015 Chevrolet Corvette Stingray Z51  29,192 mi.      3.7      (3 reviews)   
2     2020 Jeep Grand Cherokee Overland  53,561 mi.      4.8  (1,147 reviews)   
3            2019 Audi A7 3.0T Prestige  46,664 mi.      4.9  (1,831 reviews)   
4          2017 Ford Mustang GT Premium  21,726 mi.      4.0    (409 reviews)   

  used/certified         price drop    Price  
0           Used    $501 price drop  $27,995  
1           Used    $277 price drop  $52,000  
2           Used  $2,000 price drop  $41,998  
3           Used  $2,090 price drop  $62,750  
4           Used    $200 price drop  $29,995

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9330 entries, 0 to 9329
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   Car Names       9330 non-null   object 
 1   Mileages        9330 non-null   object 
 2   Ratings         9330 non-null   float64
 3   Reviews         9330 non-null   object 
 4   used/certified  9330 non-null   object 
 5   price drop      9330 non-null   object 
 6   Price           9330 non-null   object 
dtypes: float64(1), object(6)
memory usage: 510.4+ KB


#### первичный анализ
много столбцов типа object, их нужно переделать в числовые
CarNames - марка авто, сделать группировку, и заменить название на номер группы
used/certified - used заменить на 1, остальное 0
Price - убрать символы, перевеси в int
price drop  - убрать символы, перевеси в int
Reviews - убрать символы, перевеси в int
Mileages - убрать символы, перевеси в int


In [4]:
df.drop_duplicates(inplace=True)

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 4380 entries, 0 to 4379
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   Car Names       4380 non-null   object 
 1   Mileages        4380 non-null   object 
 2   Ratings         4380 non-null   float64
 3   Reviews         4380 non-null   object 
 4   used/certified  4380 non-null   object 
 5   price drop      4380 non-null   object 
 6   Price           4380 non-null   object 
dtypes: float64(1), object(6)
memory usage: 273.8+ KB


In [6]:
#в столбце прайс буду убирать символ $ из начала строки и переводить его в числоваой формат
df['Price_d'] = df['Price']
df['Price_d'].head()

0    $27,995
1    $52,000
2    $41,998
3    $62,750
4    $29,995
Name: Price_d, dtype: object

In [7]:
df['Price_d'][df['Price_d']=="Not Priced"]

111     Not Priced
2250    Not Priced
4140    Not Priced
Name: Price_d, dtype: object

In [8]:
df['Price_d'].replace(["Not Priced"], "0",regex=True, inplace=True)

In [9]:
df['Price_d'].replace(["\D+"], "",regex=True, inplace=True)
df['Price_d'] = df['Price_d'].astype(int)
df['Price_d'].head()

0    27995
1    52000
2    41998
3    62750
4    29995
Name: Price_d, dtype: int32

In [10]:
df['used']=df['used/certified']
# df.rename(columns={'used/certified': 'used'}, inplace=True)

In [11]:
df['used'] = df.apply(lambda x: 1 if x['used']=='Used' else 0, axis=1)
df.head()

Car Names    Mileages  Ratings          Reviews  \
0               2019 Honda Accord Sport     Mileage      3.7      (3 reviews)   
1  2015 Chevrolet Corvette Stingray Z51  29,192 mi.      3.7      (3 reviews)   
2     2020 Jeep Grand Cherokee Overland  53,561 mi.      4.8  (1,147 reviews)   
3            2019 Audi A7 3.0T Prestige  46,664 mi.      4.9  (1,831 reviews)   
4          2017 Ford Mustang GT Premium  21,726 mi.      4.0    (409 reviews)   

  used/certified         price drop    Price  Price_d  used  
0           Used    $501 price drop  $27,995    27995     1  
1           Used    $277 price drop  $52,000    52000     1  
2           Used  $2,000 price drop  $41,998    41998     1  
3           Used  $2,090 price drop  $62,750    62750     1  
4           Used    $200 price drop  $29,995    29995     1

In [12]:
df['Reviews_d'] = df['Reviews']

In [13]:
df['Reviews_d'].replace(["\D+"], "",regex=True, inplace=True)

In [14]:
df['Reviews_d'] = df['Reviews_d'].astype(int)
df.head()

Car Names    Mileages  Ratings          Reviews  \
0               2019 Honda Accord Sport     Mileage      3.7      (3 reviews)   
1  2015 Chevrolet Corvette Stingray Z51  29,192 mi.      3.7      (3 reviews)   
2     2020 Jeep Grand Cherokee Overland  53,561 mi.      4.8  (1,147 reviews)   
3            2019 Audi A7 3.0T Prestige  46,664 mi.      4.9  (1,831 reviews)   
4          2017 Ford Mustang GT Premium  21,726 mi.      4.0    (409 reviews)   

  used/certified         price drop    Price  Price_d  used  Reviews_d  
0           Used    $501 price drop  $27,995    27995     1          3  
1           Used    $277 price drop  $52,000    52000     1          3  
2           Used  $2,000 price drop  $41,998    41998     1       1147  
3           Used  $2,090 price drop  $62,750    62750     1       1831  
4           Used    $200 price drop  $29,995    29995     1        409

In [15]:
df['price_drop'] = df['price drop']

In [16]:
df['price_drop'].replace(["\D+"], "",regex=True, inplace=True)

In [17]:
df['price_drop'] = df['price_drop'].astype(int)
df.head()

Car Names    Mileages  Ratings          Reviews  \
0               2019 Honda Accord Sport     Mileage      3.7      (3 reviews)   
1  2015 Chevrolet Corvette Stingray Z51  29,192 mi.      3.7      (3 reviews)   
2     2020 Jeep Grand Cherokee Overland  53,561 mi.      4.8  (1,147 reviews)   
3            2019 Audi A7 3.0T Prestige  46,664 mi.      4.9  (1,831 reviews)   
4          2017 Ford Mustang GT Premium  21,726 mi.      4.0    (409 reviews)   

  used/certified         price drop    Price  Price_d  used  Reviews_d  \
0           Used    $501 price drop  $27,995    27995     1          3   
1           Used    $277 price drop  $52,000    52000     1          3   
2           Used  $2,000 price drop  $41,998    41998     1       1147   
3           Used  $2,090 price drop  $62,750    62750     1       1831   
4           Used    $200 price drop  $29,995    29995     1        409   

   price_drop  
0         501  
1         277  
2        2000  
3        2090  
4         200

In [18]:
df['Mileages_d'] = df['Mileages']

In [19]:
df['Mileages_d'] = df['Mileages_d'].replace(["Mileage"], 0,regex=True)

In [20]:
df['Mileages_d'].replace(["\D+"], "",regex=True, inplace=True)

In [21]:
df['Mileages_d'] = df['Mileages_d'].astype(int)
df.head()

Car Names    Mileages  Ratings          Reviews  \
0               2019 Honda Accord Sport     Mileage      3.7      (3 reviews)   
1  2015 Chevrolet Corvette Stingray Z51  29,192 mi.      3.7      (3 reviews)   
2     2020 Jeep Grand Cherokee Overland  53,561 mi.      4.8  (1,147 reviews)   
3            2019 Audi A7 3.0T Prestige  46,664 mi.      4.9  (1,831 reviews)   
4          2017 Ford Mustang GT Premium  21,726 mi.      4.0    (409 reviews)   

  used/certified         price drop    Price  Price_d  used  Reviews_d  \
0           Used    $501 price drop  $27,995    27995     1          3   
1           Used    $277 price drop  $52,000    52000     1          3   
2           Used  $2,000 price drop  $41,998    41998     1       1147   
3           Used  $2,090 price drop  $62,750    62750     1       1831   
4           Used    $200 price drop  $29,995    29995     1        409   

   price_drop  Mileages_d  
0         501           0  
1         277       29192  
2        2000       53561  
3        2090       46664  
4         200       21726

In [22]:
df['group']=df.groupby(['Car Names'], axis=0).ngroup()
df.head()

Car Names    Mileages  Ratings          Reviews  \
0               2019 Honda Accord Sport     Mileage      3.7      (3 reviews)   
1  2015 Chevrolet Corvette Stingray Z51  29,192 mi.      3.7      (3 reviews)   
2     2020 Jeep Grand Cherokee Overland  53,561 mi.      4.8  (1,147 reviews)   
3            2019 Audi A7 3.0T Prestige  46,664 mi.      4.9  (1,831 reviews)   
4          2017 Ford Mustang GT Premium  21,726 mi.      4.0    (409 reviews)   

  used/certified         price drop    Price  Price_d  used  Reviews_d  \
0           Used    $501 price drop  $27,995    27995     1          3   
1           Used    $277 price drop  $52,000    52000     1          3   
2           Used  $2,000 price drop  $41,998    41998     1       1147   
3           Used  $2,090 price drop  $62,750    62750     1       1831   
4           Used    $200 price drop  $29,995    29995     1        409   

   price_drop  Mileages_d  group  
0         501           0    840  
1         277       29192    180  
2        2000       53561   1243  
3        2090       46664    717  
4         200       21726    390

In [23]:
df[df['Price_d']==0] = df['Price_d'].mean()

In [24]:
df[df['Mileages_d']==0] = df['Mileages_d'].mean()

In [25]:
df

Car Names      Mileages       Ratings  \
0                             34712.166821  34712.166821  34712.166821   
1     2015 Chevrolet Corvette Stingray Z51    29,192 mi.      3.700000   
2        2020 Jeep Grand Cherokee Overland    53,561 mi.      4.800000   
3               2019 Audi A7 3.0T Prestige    46,664 mi.      4.900000   
4             2017 Ford Mustang GT Premium    21,726 mi.      4.000000   
...                                    ...           ...           ...   
4375                2019 Lexus IS 300 Base    61,106 mi.      4.700000   
4376                    2019 Kia Sorento L    11,132 mi.      4.800000   
4377                2017 GMC Acadia Denali    55,074 mi.      3.400000   
4378                2019 Honda Pilot Elite    57,150 mi.      4.900000   
4379                  2019 GMC Terrain SLT    56,293 mi.      4.800000   

              Reviews   used/certified         price drop         Price  \
0        34712.166821     34712.166821       34712.166821  34712.166821   
1         (3 reviews)             Used    $277 price drop       $52,000   
2     (1,147 reviews)             Used  $2,000 price drop       $41,998   
3     (1,831 reviews)             Used  $2,090 price drop       $62,750   
4       (409 reviews)             Used    $200 price drop       $29,995   
...               ...              ...                ...           ...   
4375  (4,658 reviews)             Used  $2,770 price drop       $36,500   
4376    (505 reviews)             Used    $200 price drop       $23,450   
4377    (127 reviews)             Used  $2,065 price drop       $29,381   
4378  (8,222 reviews)  Honda Certified  $2,007 price drop       $38,488   
4379  (1,293 reviews)             Used    $561 price drop       $27,812   

           Price_d          used     Reviews_d    price_drop    Mileages_d  \
0     34712.166821  34712.166821  34712.166821  34712.166821  34712.166821   
1     52000.000000      1.000000      3.000000    277.000000  29192.000000   
2     41998.000000      1.000000   1147.000000   2000.000000  53561.000000   
3     62750.000000      1.000000   1831.000000   2090.000000  46664.000000   
4     29995.000000      1.000000    409.000000    200.000000  21726.000000   
...            ...           ...           ...           ...           ...   
4375  36500.000000      1.000000   4658.000000   2770.000000  61106.000000   
4376  23450.000000      1.000000    505.000000    200.000000  11132.000000   
4377  29381.000000      1.000000    127.000000   2065.000000  55074.000000   
4378  38488.000000      0.000000   8222.000000   2007.000000  57150.000000   
4379  27812.000000      1.000000   1293.000000    561.000000  56293.000000   

             group  
0     34712.166821  
1       180.000000  
2      1243.000000  
3       717.000000  
4       390.000000  
...            ...  
4375    918.000000  
4376    892.000000  
4377    392.000000  
4378    858.000000  
4379    833.000000  

[4380 rows x 13 columns]

In [26]:
df['test'] = df['Car Names'].str.split(' ')


In [27]:
df = df[df['test'].isna() == False]

In [53]:
df['year'] = df['test'].apply(lambda x: x[0])
df['year'] = df['year'].astype(int)

C:\Users\goninm\AppData\Local\Temp/ipykernel_1848/2893633169.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['year'] = df['test'].apply(lambda x: x[0])
C:\Users\goninm\AppData\Local\Temp/ipykernel_1848/2893633169.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['year'] = df['year'].astype(int)


In [29]:
df['Manufacture'] = df['test'].apply(lambda x: x[1])

C:\Users\goninm\AppData\Local\Temp/ipykernel_1848/1413394560.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Manufacture'] = df['test'].apply(lambda x: x[1])


In [30]:
df['model_name']=df['test'].apply(lambda x: x[2:])

C:\Users\goninm\AppData\Local\Temp/ipykernel_1848/123370241.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['model_name']=df['test'].apply(lambda x: x[2:])


In [31]:
df.head()

Car Names    Mileages  Ratings          Reviews  \
1  2015 Chevrolet Corvette Stingray Z51  29,192 mi.      3.7      (3 reviews)   
2     2020 Jeep Grand Cherokee Overland  53,561 mi.      4.8  (1,147 reviews)   
3            2019 Audi A7 3.0T Prestige  46,664 mi.      4.9  (1,831 reviews)   
4          2017 Ford Mustang GT Premium  21,726 mi.      4.0    (409 reviews)   
5      2016 Jeep Grand Cherokee Limited  66,514 mi.      4.6  (1,348 reviews)   

  used/certified         price drop    Price  Price_d  used  Reviews_d  \
1           Used    $277 price drop  $52,000  52000.0   1.0        3.0   
2           Used  $2,000 price drop  $41,998  41998.0   1.0     1147.0   
3           Used  $2,090 price drop  $62,750  62750.0   1.0     1831.0   
4           Used    $200 price drop  $29,995  29995.0   1.0      409.0   
5           Used  $2,000 price drop  $26,499  26499.0   1.0     1348.0   

   price_drop  Mileages_d   group                                        test  \
1       277.0     29192.0   180.0  [2015, Chevrolet, Corvette, Stingray, Z51]   
2      2000.0     53561.0  1243.0     [2020, Jeep, Grand, Cherokee, Overland]   
3      2090.0     46664.0   717.0            [2019, Audi, A7, 3.0T, Prestige]   
4       200.0     21726.0   390.0          [2017, Ford, Mustang, GT, Premium]   
5      2000.0     66514.0   297.0      [2016, Jeep, Grand, Cherokee, Limited]   

   year Manufacture                   model_name  
1  2015   Chevrolet    [Corvette, Stingray, Z51]  
2  2020        Jeep  [Grand, Cherokee, Overland]  
3  2019        Audi         [A7, 3.0T, Prestige]  
4  2017        Ford       [Mustang, GT, Premium]  
5  2016        Jeep   [Grand, Cherokee, Limited]

In [54]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 4277 entries, 1 to 4379
Data columns (total 17 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   Car Names       4277 non-null   object 
 1   Mileages        4277 non-null   object 
 2   Ratings         4277 non-null   float64
 3   Reviews         4277 non-null   object 
 4   used/certified  4277 non-null   object 
 5   price drop      4277 non-null   object 
 6   Price           4277 non-null   object 
 7   Price_d         4277 non-null   float64
 8   used            4277 non-null   float64
 9   Reviews_d       4277 non-null   float64
 10  price_drop      4277 non-null   float64
 11  Mileages_d      4277 non-null   float64
 12  group           4277 non-null   float64
 13  test            4277 non-null   object 
 14  year            4277 non-null   int32  
 15  Manufacture     4277 non-null   object 
 16  model_name      4277 non-null   object 
dtypes: float64(7), int32(1), object(9

In [55]:
df.sample(10)

Car Names     Mileages  Ratings  \
1314                     2016 Audi Q3 2.0T Premium Plus   46,588 mi.      4.7   
1347                    2018 Maserati GranTurismo Sport   27,533 mi.      4.8   
3758                    2020 Jaguar F-PACE 25t Prestige   50,611 mi.      2.8   
2244                             2021 Ford F-150 Lariat   30,421 mi.      4.5   
261                    2021 Honda Pilot Special Edition  132,179 mi.      4.0   
3059                              2020 Toyota Tacoma SR   46,487 mi.      2.5   
2659                               2019 Honda CR-V EX-L   32,598 mi.      4.5   
420                              2015 Dodge Durango R/T   19,137 mi.      4.7   
1035  2021 Land Rover Range Rover Sport HSE Silver E...   41,928 mi.      4.3   
3614                              2020 Ford Explorer ST   49,588 mi.      4.4   

              Reviews      used/certified         price drop    Price  \
1314    (848 reviews)                Used  $2,000 price drop  $19,441   
1347  (1,696 reviews)  Maserati Certified  $2,760 price drop  $79,900   
3758     (12 reviews)                Used    $523 price drop  $47,952   
2244    (221 reviews)                Used    $990 price drop  $61,996   
261      (72 reviews)                Used  $1,000 price drop  $41,987   
3059     (17 reviews)                Used    $585 price drop  $39,998   
2659    (616 reviews)                Used  $5,300 price drop  $33,497   
420     (136 reviews)                Used  $7,003 price drop  $29,250   
1035    (504 reviews)                Used    $500 price drop  $79,880   
3614  (2,223 reviews)      Ford Certified    $448 price drop  $48,997   

      Price_d  used  Reviews_d  price_drop  Mileages_d   group  \
1314  19441.0   1.0      848.0      2000.0     46588.0   244.0   
1347  79900.0   0.0     1696.0      2760.0     27533.0   624.0   
3758  47952.0   1.0       12.0       523.0     50611.0  1233.0   
2244  61996.0   1.0      221.0       990.0     30421.0  1483.0   
261   41987.0   1.0       72.0      1000.0    132179.0  1518.0   
3059  39998.0   1.0       17.0       585.0     46487.0  1378.0   
2659  33497.0   1.0      616.0      5300.0     32598.0   842.0   
420   29250.0   1.0      136.0      7003.0     19137.0   187.0   
1035  79880.0   1.0      504.0       500.0     41928.0  1561.0   
3614  48997.0   0.0     2223.0       448.0     49588.0  1169.0   

                                                   test  year Manufacture  \
1314              [2016, Audi, Q3, 2.0T, Premium, Plus]  2016        Audi   
1347               [2018, Maserati, GranTurismo, Sport]  2018    Maserati   
3758              [2020, Jaguar, F-PACE, 25t, Prestige]  2020      Jaguar   
2244                        [2021, Ford, F-150, Lariat]  2021        Ford   
261              [2021, Honda, Pilot, Special, Edition]  2021       Honda   
3059                         [2020, Toyota, Tacoma, SR]  2020      Toyota   
2659                          [2019, Honda, CR-V, EX-L]  2019       Honda   
420                         [2015, Dodge, Durango, R/T]  2015       Dodge   
1035  [2021, Land, Rover, Range, Rover, Sport, HSE, ...  2021        Land   
3614                         [2020, Ford, Explorer, ST]  2020        Ford   

                                             model_name  
1314                          [Q3, 2.0T, Premium, Plus]  
1347                               [GranTurismo, Sport]  
3758                            [F-PACE, 25t, Prestige]  
2244                                    [F-150, Lariat]  
261                           [Pilot, Special, Edition]  
3059                                       [Tacoma, SR]  
2659                                       [CR-V, EX-L]  
420                                      [Durango, R/T]  
1035  [Rover, Range, Rover, Sport, HSE, Silver, Edit...  
3614                                     [Explorer, ST]

In [56]:
df.describe()

Ratings        Price_d         used     Reviews_d    price_drop  \
count  4277.000000    4277.000000  4277.000000   4277.000000   4277.000000   
mean      4.486720   41848.259995     0.836801   1134.119009   1152.564181   
std       0.466659   27049.022630     0.369590   1875.937754   1459.814278   
min       1.400000    3595.000000     0.000000      0.000000    100.000000   
25%       4.400000   29490.000000     1.000000    152.000000    491.000000   
50%       4.600000   36998.000000     1.000000    620.000000    890.000000   
75%       4.800000   47988.000000     1.000000   1372.000000   1368.000000   
max       5.000000  899000.000000     1.000000  27885.000000  40000.000000   

          Mileages_d        group         year  
count    4277.000000  4277.000000  4277.000000  
mean    35518.861585   969.390227  2018.917699  
std     25877.814371   438.265746     2.200807  
min       143.000000     0.000000  1997.000000  
25%     17279.000000   683.000000  2018.000000  
50%     28406.000000   962.000000  2019.000000  
75%     46609.000000  1332.000000  2020.000000  
max    277281.000000  1745.000000  2022.000000

### Numpy

In [36]:
import numpy as np

1. Вычислите A + B, A - B
 
 $\\
A = \left(
\begin{array}{cccc}
1 & -2 & 4\\
2 & 0 & -1\\
\end{array}
\right), B = \left(
\begin{array}{cccc}
5 & 2 & 3\\
4 & 6 & 2\\
\end{array}
\right)$

In [37]:
A = np.array([[1,-2,4],[2,0,-1]])
A

array([[ 1, -2,  4],
       [ 2,  0, -1]])

In [38]:
B = np.array([[5,2,3],[4,6,2]])
B

array([[5, 2, 3],
       [4, 6, 2]])

In [39]:
A+B

array([[6, 0, 7],
       [6, 6, 1]])

In [40]:
A-B

array([[-4, -4,  1],
       [-2, -6, -3]])

2. Найдите матрицу С = A - 3B
 
 $\\
A = \left(
\begin{array}{cccc}
1 & 2 \\
2 & -1\\
3 & 0\\
\end{array}
\right), B = \left(
\begin{array}{cccc}
-1 & 1 \\
1 & 2\\
0 & 0\\
\end{array}
\right)$

In [41]:
A = np.array([[1,2],[2,-1],[3,0]])
A

array([[ 1,  2],
       [ 2, -1],
       [ 3,  0]])

In [42]:
B = np.array([[-1,1],[1,2],[0,0]])
B

array([[-1,  1],
       [ 1,  2],
       [ 0,  0]])

In [43]:
C = A -3*B
C

array([[ 4, -1],
       [-1, -7],
       [ 3,  0]])

3. Вычислите С = AB
 
 $\\
A = \left(
\begin{array}{cccc}
1 & -1 \\
2 & 0\\
3 & 0\\
\end{array}
\right), B = \left(
\begin{array}{cccc}
1 & 1 \\
2 & 0\\
\end{array}
\right)$

In [44]:
A = np.array([[1,-1],[2,0],[3,0]])
A

array([[ 1, -1],
       [ 2,  0],
       [ 3,  0]])

In [45]:
B = np.array([[1,1],[2,0]])
B

array([[1, 1],
       [2, 0]])

In [46]:
C=A.dot(B)
C

array([[-1,  1],
       [ 2,  2],
       [ 3,  3]])

4. Вычислите определитель матрицы А
 
 $\\
A = \left(
\begin{array}{cccc}
6 & -1 & 4\\
2 & 1 & 10\\
8 & 0 & 2\\
\end{array}
\right)$

In [47]:
A = np.array([[6,-1,4],[2,1,10],[8,0,2]])
A

array([[ 6, -1,  4],
       [ 2,  1, 10],
       [ 8,  0,  2]])

In [48]:
np.linalg.det(A)

-95.99999999999999

5. Вычислите матрицу, обратную матрице А. И покажите, что она действительно является обратной
 
 $\\
A = \left(
\begin{array}{cccc}
3 & 3 & -1\\
4 & 1 & 3\\
1 & -2 & -2\\
\end{array}
\right)$

In [49]:
A = np.array([[3,3,-1],[4,1,3],[1,-2,-2]])
A

array([[ 3,  3, -1],
       [ 4,  1,  3],
       [ 1, -2, -2]])

In [50]:
An = np.linalg.inv(A)
An

array([[ 0.07407407,  0.14814815,  0.18518519],
       [ 0.2037037 , -0.09259259, -0.24074074],
       [-0.16666667,  0.16666667, -0.16666667]])

In [51]:
C = A.dot(An)
C

array([[ 1.00000000e+00, -8.32667268e-17,  2.77555756e-17],
       [ 2.77555756e-17,  1.00000000e+00,  2.77555756e-17],
       [-5.55111512e-17,  5.55111512e-17,  1.00000000e+00]])

In [52]:
# можно считать, что на главной диагонали стят 1, а остлаьные элементы 0