### Pandas

* Скачайте любой табличный датасет (можете использовать тот же, что и в дз к занятию "Знакомство с библиотеками"), например, с https://www.kaggle.com/datasets
* Проведите поноценный EDA 
    * "погрузитесь" в данные
    * составьте описание измерений из датасета
    * очистите данные, если это необходимо
    * попробуйте создать дополнительные переменные, которые могут помочь лучше понять данные

In [288]:
import pandas as pd


In [289]:
df = pd.read_csv('new-used-cars-dataset.csv')
df.head()

Car Names    Mileages  Ratings          Reviews  \
0               2019 Honda Accord Sport     Mileage      3.7      (3 reviews)   
1  2015 Chevrolet Corvette Stingray Z51  29,192 mi.      3.7      (3 reviews)   
2     2020 Jeep Grand Cherokee Overland  53,561 mi.      4.8  (1,147 reviews)   
3            2019 Audi A7 3.0T Prestige  46,664 mi.      4.9  (1,831 reviews)   
4          2017 Ford Mustang GT Premium  21,726 mi.      4.0    (409 reviews)   

  used/certified         price drop    Price  
0           Used    $501 price drop  $27,995  
1           Used    $277 price drop  $52,000  
2           Used  $2,000 price drop  $41,998  
3           Used  $2,090 price drop  $62,750  
4           Used    $200 price drop  $29,995

In [290]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9330 entries, 0 to 9329
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   Car Names       9330 non-null   object 
 1   Mileages        9330 non-null   object 
 2   Ratings         9330 non-null   float64
 3   Reviews         9330 non-null   object 
 4   used/certified  9330 non-null   object 
 5   price drop      9330 non-null   object 
 6   Price           9330 non-null   object 
dtypes: float64(1), object(6)
memory usage: 510.4+ KB


#### первичный анализ
много столбцов типа object, их нужно переделать в числовые
CarNames - марка авто, сделать группировку, и заменить название на номер группы
used/certified - used заменить на 1, остальное 0
Price - убрать символы, перевеси в int
price drop  - убрать символы, перевеси в int
Reviews - убрать символы, перевеси в int
Mileages - убрать символы, перевеси в int


In [321]:
#в столбце прайс буду убирать символ $ из начала строки и переводить его в числоваой формат
df['Price_d'] = df['Price']
df['Price_d'].head()

0    $27,995
1    $52,000
2    $41,998
3    $62,750
4    $29,995
Name: Price_d, dtype: object

In [322]:
df['Price_d'][df['Price_d']=="Not Priced"]

111     Not Priced
2250    Not Priced
4140    Not Priced
Name: Price_d, dtype: object

In [323]:
df['Price_d'].replace(["Not Priced"], "0",regex=True, inplace=True)

In [330]:
df['Price_d'].replace(["\D+"], "",regex=True, inplace=True)
df['Price_d'] = df['Price_d'].astype(int)
df['Price_d'].head()

0    27995
1    52000
2    41998
3    62750
4    29995
Name: Price_d, dtype: int32

In [331]:
df['used']=df['used/certified']
# df.rename(columns={'used/certified': 'used'}, inplace=True)

In [332]:
df['used'] = df.apply(lambda x: 1 if x['used']=='Used' else 0, axis=1)
df.head()

Car Names    Mileages  Ratings          Reviews  \
0               2019 Honda Accord Sport     Mileage      3.7      (3 reviews)   
1  2015 Chevrolet Corvette Stingray Z51  29,192 mi.      3.7      (3 reviews)   
2     2020 Jeep Grand Cherokee Overland  53,561 mi.      4.8  (1,147 reviews)   
3            2019 Audi A7 3.0T Prestige  46,664 mi.      4.9  (1,831 reviews)   
4          2017 Ford Mustang GT Premium  21,726 mi.      4.0    (409 reviews)   

  used/certified         price drop    Price  Price_d  used  
0           Used    $501 price drop  $27,995    27995     1  
1           Used    $277 price drop  $52,000    52000     1  
2           Used  $2,000 price drop  $41,998    41998     1  
3           Used  $2,090 price drop  $62,750    62750     1  
4           Used    $200 price drop  $29,995    29995     1

In [333]:
df['Reviews_d'] = df['Reviews']

In [334]:
df['Reviews_d'].replace(["\D+"], "",regex=True, inplace=True)

In [338]:
df['Reviews_d'] = df['Reviews_d'].astype(int)
df.head()

Car Names    Mileages  Ratings          Reviews  \
0               2019 Honda Accord Sport     Mileage      3.7      (3 reviews)   
1  2015 Chevrolet Corvette Stingray Z51  29,192 mi.      3.7      (3 reviews)   
2     2020 Jeep Grand Cherokee Overland  53,561 mi.      4.8  (1,147 reviews)   
3            2019 Audi A7 3.0T Prestige  46,664 mi.      4.9  (1,831 reviews)   
4          2017 Ford Mustang GT Premium  21,726 mi.      4.0    (409 reviews)   

  used/certified         price drop    Price  Price_d  used  Reviews_d  
0           Used    $501 price drop  $27,995    27995     1          3  
1           Used    $277 price drop  $52,000    52000     1          3  
2           Used  $2,000 price drop  $41,998    41998     1       1147  
3           Used  $2,090 price drop  $62,750    62750     1       1831  
4           Used    $200 price drop  $29,995    29995     1        409

In [339]:
df['price_drop'] = df['price drop']

In [340]:
df['price_drop'].replace(["\D+"], "",regex=True, inplace=True)

In [341]:
df['price_drop'] = df['price_drop'].astype(int)
df.head()

Car Names    Mileages  Ratings          Reviews  \
0               2019 Honda Accord Sport     Mileage      3.7      (3 reviews)   
1  2015 Chevrolet Corvette Stingray Z51  29,192 mi.      3.7      (3 reviews)   
2     2020 Jeep Grand Cherokee Overland  53,561 mi.      4.8  (1,147 reviews)   
3            2019 Audi A7 3.0T Prestige  46,664 mi.      4.9  (1,831 reviews)   
4          2017 Ford Mustang GT Premium  21,726 mi.      4.0    (409 reviews)   

  used/certified         price drop    Price  Price_d  used  Reviews_d  \
0           Used    $501 price drop  $27,995    27995     1          3   
1           Used    $277 price drop  $52,000    52000     1          3   
2           Used  $2,000 price drop  $41,998    41998     1       1147   
3           Used  $2,090 price drop  $62,750    62750     1       1831   
4           Used    $200 price drop  $29,995    29995     1        409   

   price_drop  
0         501  
1         277  
2        2000  
3        2090  
4         200

In [342]:
df['Mileages_d'] = df['Mileages']

In [343]:
df['Mileages_d'] = df['Mileages_d'].replace(["Mileage"], 0,regex=True)

In [344]:
df['Mileages_d'].replace(["\D+"], "",regex=True, inplace=True)

In [346]:
df['Mileages_d'] = df['Mileages_d'].astype(int)
df.head()

Car Names    Mileages  Ratings          Reviews  \
0               2019 Honda Accord Sport     Mileage      3.7      (3 reviews)   
1  2015 Chevrolet Corvette Stingray Z51  29,192 mi.      3.7      (3 reviews)   
2     2020 Jeep Grand Cherokee Overland  53,561 mi.      4.8  (1,147 reviews)   
3            2019 Audi A7 3.0T Prestige  46,664 mi.      4.9  (1,831 reviews)   
4          2017 Ford Mustang GT Premium  21,726 mi.      4.0    (409 reviews)   

  used/certified         price drop    Price  Price_d  used  Reviews_d  \
0           Used    $501 price drop  $27,995    27995     1          3   
1           Used    $277 price drop  $52,000    52000     1          3   
2           Used  $2,000 price drop  $41,998    41998     1       1147   
3           Used  $2,090 price drop  $62,750    62750     1       1831   
4           Used    $200 price drop  $29,995    29995     1        409   

   price_drop  Mileages_d  
0         501           0  
1         277       29192  
2        2000       53561  
3        2090       46664  
4         200       21726

In [348]:
df['group']=df.groupby(['Car Names'], axis=0).ngroup()
df.head()

Car Names    Mileages  Ratings          Reviews  \
0               2019 Honda Accord Sport     Mileage      3.7      (3 reviews)   
1  2015 Chevrolet Corvette Stingray Z51  29,192 mi.      3.7      (3 reviews)   
2     2020 Jeep Grand Cherokee Overland  53,561 mi.      4.8  (1,147 reviews)   
3            2019 Audi A7 3.0T Prestige  46,664 mi.      4.9  (1,831 reviews)   
4          2017 Ford Mustang GT Premium  21,726 mi.      4.0    (409 reviews)   

  used/certified         price drop    Price  Price_d  used  Reviews_d  \
0           Used    $501 price drop  $27,995    27995     1          3   
1           Used    $277 price drop  $52,000    52000     1          3   
2           Used  $2,000 price drop  $41,998    41998     1       1147   
3           Used  $2,090 price drop  $62,750    62750     1       1831   
4           Used    $200 price drop  $29,995    29995     1        409   

   price_drop  Mileages_d  group  
0         501           0    840  
1         277       29192    180  
2        2000       53561   1243  
3        2090       46664    717  
4         200       21726    390

In [352]:
df[df['Price_d']==0] = df['Price_d'].mean()

In [353]:
df[df['Mileages_d']==0] = df['Mileages_d'].mean()

In [354]:
df.describe()

Ratings        Price_d          used     Reviews_d    price_drop  \
count   9330.000000    9330.000000   9330.000000   9330.000000   9330.000000   
mean     797.004829   42024.707423    793.433361   2073.324893   1967.299063   
std     5328.574911   23910.414691   5329.106142   5570.395520   5348.196507   
min        1.400000    3595.000000      0.000000      0.000000    100.000000   
25%        4.400000   29291.250000      1.000000    170.000000    500.000000   
50%        4.600000   36862.500000      1.000000    570.000000    835.000000   
75%        4.800000   47968.000000      1.000000   1636.000000   1644.000000   
max    41780.835798  899000.000000  41780.835798  41780.835798  41780.835798   

          Mileages_d         group  
count    9330.000000   9330.000000  
mean    37310.601206   1732.081378  
std     25492.206515   5208.619754  
min       143.000000      0.000000  
25%     18596.000000    618.250000  
50%     31389.500000    938.000000  
75%     48061.500000   1368.750000  
max    277281.000000  41780.835798

### Numpy

In [287]:
import numpy as np

1. Вычислите A + B, A - B
 
 $\\
A = \left(
\begin{array}{cccc}
1 & -2 & 4\\
2 & 0 & -1\\
\end{array}
\right), B = \left(
\begin{array}{cccc}
5 & 2 & 3\\
4 & 6 & 2\\
\end{array}
\right)$

In [365]:
A = np.array([[1,-2,4],[2,0,-1]])
A

array([[ 1, -2,  4],
       [ 2,  0, -1]])

In [366]:
B = np.array([[5,2,3],[4,6,2]])
B

array([[5, 2, 3],
       [4, 6, 2]])

In [367]:
A+B

array([[6, 0, 7],
       [6, 6, 1]])

In [368]:
A-B

array([[-4, -4,  1],
       [-2, -6, -3]])

2. Найдите матрицу С = A - 3B
 
 $\\
A = \left(
\begin{array}{cccc}
1 & 2 \\
2 & -1\\
3 & 0\\
\end{array}
\right), B = \left(
\begin{array}{cccc}
-1 & 1 \\
1 & 2\\
0 & 0\\
\end{array}
\right)$

In [369]:
A = np.array([[1,2],[2,-1],[3,0]])
A

array([[ 1,  2],
       [ 2, -1],
       [ 3,  0]])

In [370]:
B = np.array([[-1,1],[1,2],[0,0]])
B

array([[-1,  1],
       [ 1,  2],
       [ 0,  0]])

In [372]:
C = A -3*B
C

array([[ 4, -1],
       [-1, -7],
       [ 3,  0]])

3. Вычислите С = AB
 
 $\\
A = \left(
\begin{array}{cccc}
1 & -1 \\
2 & 0\\
3 & 0\\
\end{array}
\right), B = \left(
\begin{array}{cccc}
1 & 1 \\
2 & 0\\
\end{array}
\right)$

In [373]:
A = np.array([[1,-1],[2,0],[3,0]])
A

array([[ 1, -1],
       [ 2,  0],
       [ 3,  0]])

In [374]:
B = np.array([[1,1],[2,0]])
B

array([[1, 1],
       [2, 0]])

In [376]:
C=A.dot(B)
C

array([[-1,  1],
       [ 2,  2],
       [ 3,  3]])

4. Вычислите определитель матрицы А
 
 $\\
A = \left(
\begin{array}{cccc}
6 & -1 & 4\\
2 & 1 & 10\\
8 & 0 & 2\\
\end{array}
\right)$

In [377]:
A = np.array([[6,-1,4],[2,1,10],[8,0,2]])
A

array([[ 6, -1,  4],
       [ 2,  1, 10],
       [ 8,  0,  2]])

In [388]:
np.linalg.det(A)

53.999999999999986

5. Вычислите матрицу, обратную матрице А. И покажите, что она действительно является обратной
 
 $\\
A = \left(
\begin{array}{cccc}
3 & 3 & -1\\
4 & 1 & 3\\
1 & -2 & -2\\
\end{array}
\right)$

In [403]:
A = np.array([[3,3,-1],[4,1,3],[1,-2,-2]])
A

array([[ 3,  3, -1],
       [ 4,  1,  3],
       [ 1, -2, -2]])

In [404]:
An = np.linalg.inv(A)
An

array([[ 0.07407407,  0.14814815,  0.18518519],
       [ 0.2037037 , -0.09259259, -0.24074074],
       [-0.16666667,  0.16666667, -0.16666667]])

In [405]:
C = A.dot(At)
C

array([[ 1.00000000e+00, -8.32667268e-17,  2.77555756e-17],
       [ 2.77555756e-17,  1.00000000e+00,  2.77555756e-17],
       [-5.55111512e-17,  5.55111512e-17,  1.00000000e+00]])

In [ ]:
# можно считать, что на главной диагонали стят 1, а остлаьные элементы 0