### Pandas

* Скачайте любой табличный датасет (можете использовать тот же, что и в дз к занятию "Знакомство с библиотеками"), например, с https://www.kaggle.com/datasets
* Проведите поноценный EDA 
    * "погрузитесь" в данные
    * составьте описание измерений из датасета
    * очистите данные, если это необходимо
    * попробуйте создать дополнительные переменные, которые могут помочь лучше понять данные

In [1]:
import pandas as pd


In [2]:
df = pd.read_csv('new-used-cars-dataset.csv')
df.head()

Car Names    Mileages  Ratings          Reviews  \
0               2019 Honda Accord Sport     Mileage      3.7      (3 reviews)   
1  2015 Chevrolet Corvette Stingray Z51  29,192 mi.      3.7      (3 reviews)   
2     2020 Jeep Grand Cherokee Overland  53,561 mi.      4.8  (1,147 reviews)   
3            2019 Audi A7 3.0T Prestige  46,664 mi.      4.9  (1,831 reviews)   
4          2017 Ford Mustang GT Premium  21,726 mi.      4.0    (409 reviews)   

  used/certified         price drop    Price  
0           Used    $501 price drop  $27,995  
1           Used    $277 price drop  $52,000  
2           Used  $2,000 price drop  $41,998  
3           Used  $2,090 price drop  $62,750  
4           Used    $200 price drop  $29,995

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9330 entries, 0 to 9329
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   Car Names       9330 non-null   object 
 1   Mileages        9330 non-null   object 
 2   Ratings         9330 non-null   float64
 3   Reviews         9330 non-null   object 
 4   used/certified  9330 non-null   object 
 5   price drop      9330 non-null   object 
 6   Price           9330 non-null   object 
dtypes: float64(1), object(6)
memory usage: 510.4+ KB


#### первичный анализ
много столбцов типа object, их нужно переделать в числовые
CarNames - марка авто, сделать группировку, и заменить название на номер группы
used/certified - used заменить на 1, остальное 0
Price - убрать символы, перевеси в int
price drop  - убрать символы, перевеси в int
Reviews - убрать символы, перевеси в int
Mileages - убрать символы, перевеси в int


In [4]:
df.drop_duplicates(inplace=True)

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 4380 entries, 0 to 4379
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   Car Names       4380 non-null   object 
 1   Mileages        4380 non-null   object 
 2   Ratings         4380 non-null   float64
 3   Reviews         4380 non-null   object 
 4   used/certified  4380 non-null   object 
 5   price drop      4380 non-null   object 
 6   Price           4380 non-null   object 
dtypes: float64(1), object(6)
memory usage: 273.8+ KB


In [6]:
#в столбце прайс буду убирать символ $ из начала строки и переводить его в числоваой формат
df['Price_d'] = df['Price']
df['Price_d'].head()

0    $27,995
1    $52,000
2    $41,998
3    $62,750
4    $29,995
Name: Price_d, dtype: object

In [7]:
df['Price_d'][df['Price_d']=="Not Priced"]

111     Not Priced
2250    Not Priced
4140    Not Priced
Name: Price_d, dtype: object

In [8]:
df['Price_d'].replace(["Not Priced"], "0",regex=True, inplace=True)

In [9]:
df['Price_d'].replace(["\D+"], "",regex=True, inplace=True)
df['Price_d'] = df['Price_d'].astype(int)
df['Price_d'].head()

0    27995
1    52000
2    41998
3    62750
4    29995
Name: Price_d, dtype: int32

In [10]:
df['used']=df['used/certified']
# df.rename(columns={'used/certified': 'used'}, inplace=True)

In [11]:
df['used'] = df.apply(lambda x: 1 if x['used']=='Used' else 0, axis=1)
df.head()

Car Names    Mileages  Ratings          Reviews  \
0               2019 Honda Accord Sport     Mileage      3.7      (3 reviews)   
1  2015 Chevrolet Corvette Stingray Z51  29,192 mi.      3.7      (3 reviews)   
2     2020 Jeep Grand Cherokee Overland  53,561 mi.      4.8  (1,147 reviews)   
3            2019 Audi A7 3.0T Prestige  46,664 mi.      4.9  (1,831 reviews)   
4          2017 Ford Mustang GT Premium  21,726 mi.      4.0    (409 reviews)   

  used/certified         price drop    Price  Price_d  used  
0           Used    $501 price drop  $27,995    27995     1  
1           Used    $277 price drop  $52,000    52000     1  
2           Used  $2,000 price drop  $41,998    41998     1  
3           Used  $2,090 price drop  $62,750    62750     1  
4           Used    $200 price drop  $29,995    29995     1

In [12]:
df['Reviews_d'] = df['Reviews']

In [13]:
df['Reviews_d'].replace(["\D+"], "",regex=True, inplace=True)

In [14]:
df['Reviews_d'] = df['Reviews_d'].astype(int)
df.head()

Car Names    Mileages  Ratings          Reviews  \
0               2019 Honda Accord Sport     Mileage      3.7      (3 reviews)   
1  2015 Chevrolet Corvette Stingray Z51  29,192 mi.      3.7      (3 reviews)   
2     2020 Jeep Grand Cherokee Overland  53,561 mi.      4.8  (1,147 reviews)   
3            2019 Audi A7 3.0T Prestige  46,664 mi.      4.9  (1,831 reviews)   
4          2017 Ford Mustang GT Premium  21,726 mi.      4.0    (409 reviews)   

  used/certified         price drop    Price  Price_d  used  Reviews_d  
0           Used    $501 price drop  $27,995    27995     1          3  
1           Used    $277 price drop  $52,000    52000     1          3  
2           Used  $2,000 price drop  $41,998    41998     1       1147  
3           Used  $2,090 price drop  $62,750    62750     1       1831  
4           Used    $200 price drop  $29,995    29995     1        409

In [15]:
df['price_drop'] = df['price drop']

In [16]:
df['price_drop'].replace(["\D+"], "",regex=True, inplace=True)

In [17]:
df['price_drop'] = df['price_drop'].astype(int)
df.head()

Car Names    Mileages  Ratings          Reviews  \
0               2019 Honda Accord Sport     Mileage      3.7      (3 reviews)   
1  2015 Chevrolet Corvette Stingray Z51  29,192 mi.      3.7      (3 reviews)   
2     2020 Jeep Grand Cherokee Overland  53,561 mi.      4.8  (1,147 reviews)   
3            2019 Audi A7 3.0T Prestige  46,664 mi.      4.9  (1,831 reviews)   
4          2017 Ford Mustang GT Premium  21,726 mi.      4.0    (409 reviews)   

  used/certified         price drop    Price  Price_d  used  Reviews_d  \
0           Used    $501 price drop  $27,995    27995     1          3   
1           Used    $277 price drop  $52,000    52000     1          3   
2           Used  $2,000 price drop  $41,998    41998     1       1147   
3           Used  $2,090 price drop  $62,750    62750     1       1831   
4           Used    $200 price drop  $29,995    29995     1        409   

   price_drop  
0         501  
1         277  
2        2000  
3        2090  
4         200

In [18]:
df['Mileages_d'] = df['Mileages']

In [19]:
df['Mileages_d'] = df['Mileages_d'].replace(["Mileage"], 0,regex=True)

In [20]:
df['Mileages_d'].replace(["\D+"], "",regex=True, inplace=True)

In [21]:
df['Mileages_d'] = df['Mileages_d'].astype(int)
df.head()

Car Names    Mileages  Ratings          Reviews  \
0               2019 Honda Accord Sport     Mileage      3.7      (3 reviews)   
1  2015 Chevrolet Corvette Stingray Z51  29,192 mi.      3.7      (3 reviews)   
2     2020 Jeep Grand Cherokee Overland  53,561 mi.      4.8  (1,147 reviews)   
3            2019 Audi A7 3.0T Prestige  46,664 mi.      4.9  (1,831 reviews)   
4          2017 Ford Mustang GT Premium  21,726 mi.      4.0    (409 reviews)   

  used/certified         price drop    Price  Price_d  used  Reviews_d  \
0           Used    $501 price drop  $27,995    27995     1          3   
1           Used    $277 price drop  $52,000    52000     1          3   
2           Used  $2,000 price drop  $41,998    41998     1       1147   
3           Used  $2,090 price drop  $62,750    62750     1       1831   
4           Used    $200 price drop  $29,995    29995     1        409   

   price_drop  Mileages_d  
0         501           0  
1         277       29192  
2        2000       53561  
3        2090       46664  
4         200       21726

In [22]:
df['group']=df.groupby(['Car Names'], axis=0).ngroup()
df.head()

Car Names    Mileages  Ratings          Reviews  \
0               2019 Honda Accord Sport     Mileage      3.7      (3 reviews)   
1  2015 Chevrolet Corvette Stingray Z51  29,192 mi.      3.7      (3 reviews)   
2     2020 Jeep Grand Cherokee Overland  53,561 mi.      4.8  (1,147 reviews)   
3            2019 Audi A7 3.0T Prestige  46,664 mi.      4.9  (1,831 reviews)   
4          2017 Ford Mustang GT Premium  21,726 mi.      4.0    (409 reviews)   

  used/certified         price drop    Price  Price_d  used  Reviews_d  \
0           Used    $501 price drop  $27,995    27995     1          3   
1           Used    $277 price drop  $52,000    52000     1          3   
2           Used  $2,000 price drop  $41,998    41998     1       1147   
3           Used  $2,090 price drop  $62,750    62750     1       1831   
4           Used    $200 price drop  $29,995    29995     1        409   

   price_drop  Mileages_d  group  
0         501           0    840  
1         277       29192    180  
2        2000       53561   1243  
3        2090       46664    717  
4         200       21726    390

In [23]:
df[df['Price_d']==0] = df['Price_d'].mean()

In [24]:
df[df['Mileages_d']==0] = df['Mileages_d'].mean()

In [25]:
df

Car Names      Mileages       Ratings  \
0                             34712.166821  34712.166821  34712.166821   
1     2015 Chevrolet Corvette Stingray Z51    29,192 mi.      3.700000   
2        2020 Jeep Grand Cherokee Overland    53,561 mi.      4.800000   
3               2019 Audi A7 3.0T Prestige    46,664 mi.      4.900000   
4             2017 Ford Mustang GT Premium    21,726 mi.      4.000000   
...                                    ...           ...           ...   
4375                2019 Lexus IS 300 Base    61,106 mi.      4.700000   
4376                    2019 Kia Sorento L    11,132 mi.      4.800000   
4377                2017 GMC Acadia Denali    55,074 mi.      3.400000   
4378                2019 Honda Pilot Elite    57,150 mi.      4.900000   
4379                  2019 GMC Terrain SLT    56,293 mi.      4.800000   

              Reviews   used/certified         price drop         Price  \
0        34712.166821     34712.166821       34712.166821  34712.166821   
1         (3 reviews)             Used    $277 price drop       $52,000   
2     (1,147 reviews)             Used  $2,000 price drop       $41,998   
3     (1,831 reviews)             Used  $2,090 price drop       $62,750   
4       (409 reviews)             Used    $200 price drop       $29,995   
...               ...              ...                ...           ...   
4375  (4,658 reviews)             Used  $2,770 price drop       $36,500   
4376    (505 reviews)             Used    $200 price drop       $23,450   
4377    (127 reviews)             Used  $2,065 price drop       $29,381   
4378  (8,222 reviews)  Honda Certified  $2,007 price drop       $38,488   
4379  (1,293 reviews)             Used    $561 price drop       $27,812   

           Price_d          used     Reviews_d    price_drop    Mileages_d  \
0     34712.166821  34712.166821  34712.166821  34712.166821  34712.166821   
1     52000.000000      1.000000      3.000000    277.000000  29192.000000   
2     41998.000000      1.000000   1147.000000   2000.000000  53561.000000   
3     62750.000000      1.000000   1831.000000   2090.000000  46664.000000   
4     29995.000000      1.000000    409.000000    200.000000  21726.000000   
...            ...           ...           ...           ...           ...   
4375  36500.000000      1.000000   4658.000000   2770.000000  61106.000000   
4376  23450.000000      1.000000    505.000000    200.000000  11132.000000   
4377  29381.000000      1.000000    127.000000   2065.000000  55074.000000   
4378  38488.000000      0.000000   8222.000000   2007.000000  57150.000000   
4379  27812.000000      1.000000   1293.000000    561.000000  56293.000000   

             group  
0     34712.166821  
1       180.000000  
2      1243.000000  
3       717.000000  
4       390.000000  
...            ...  
4375    918.000000  
4376    892.000000  
4377    392.000000  
4378    858.000000  
4379    833.000000  

[4380 rows x 13 columns]

In [26]:
df['test'] = df['Car Names'].str.split(' ')


In [27]:
df = df[df['test'].isna() == False]

In [28]:
df['year'] = df['test'].apply(lambda x: x[0])
df['year'] = df['year'].astype(int)

C:\Users\goninm\AppData\Local\Temp/ipykernel_15636/2893633169.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['year'] = df['test'].apply(lambda x: x[0])
C:\Users\goninm\AppData\Local\Temp/ipykernel_15636/2893633169.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['year'] = df['year'].astype(int)


In [29]:
df['Manufacture'] = df['test'].apply(lambda x: x[1])

C:\Users\goninm\AppData\Local\Temp/ipykernel_15636/1413394560.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Manufacture'] = df['test'].apply(lambda x: x[1])


In [30]:
df['model_name']=df['test'].apply(lambda x: x[2:])

C:\Users\goninm\AppData\Local\Temp/ipykernel_15636/123370241.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['model_name']=df['test'].apply(lambda x: x[2:])


In [31]:
df.head()

Car Names    Mileages  Ratings          Reviews  \
1  2015 Chevrolet Corvette Stingray Z51  29,192 mi.      3.7      (3 reviews)   
2     2020 Jeep Grand Cherokee Overland  53,561 mi.      4.8  (1,147 reviews)   
3            2019 Audi A7 3.0T Prestige  46,664 mi.      4.9  (1,831 reviews)   
4          2017 Ford Mustang GT Premium  21,726 mi.      4.0    (409 reviews)   
5      2016 Jeep Grand Cherokee Limited  66,514 mi.      4.6  (1,348 reviews)   

  used/certified         price drop    Price  Price_d  used  Reviews_d  \
1           Used    $277 price drop  $52,000  52000.0   1.0        3.0   
2           Used  $2,000 price drop  $41,998  41998.0   1.0     1147.0   
3           Used  $2,090 price drop  $62,750  62750.0   1.0     1831.0   
4           Used    $200 price drop  $29,995  29995.0   1.0      409.0   
5           Used  $2,000 price drop  $26,499  26499.0   1.0     1348.0   

   price_drop  Mileages_d   group                                        test  \
1       277.0     29192.0   180.0  [2015, Chevrolet, Corvette, Stingray, Z51]   
2      2000.0     53561.0  1243.0     [2020, Jeep, Grand, Cherokee, Overland]   
3      2090.0     46664.0   717.0            [2019, Audi, A7, 3.0T, Prestige]   
4       200.0     21726.0   390.0          [2017, Ford, Mustang, GT, Premium]   
5      2000.0     66514.0   297.0      [2016, Jeep, Grand, Cherokee, Limited]   

   year Manufacture                   model_name  
1  2015   Chevrolet    [Corvette, Stingray, Z51]  
2  2020        Jeep  [Grand, Cherokee, Overland]  
3  2019        Audi         [A7, 3.0T, Prestige]  
4  2017        Ford       [Mustang, GT, Premium]  
5  2016        Jeep   [Grand, Cherokee, Limited]

In [32]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 4277 entries, 1 to 4379
Data columns (total 17 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   Car Names       4277 non-null   object 
 1   Mileages        4277 non-null   object 
 2   Ratings         4277 non-null   float64
 3   Reviews         4277 non-null   object 
 4   used/certified  4277 non-null   object 
 5   price drop      4277 non-null   object 
 6   Price           4277 non-null   object 
 7   Price_d         4277 non-null   float64
 8   used            4277 non-null   float64
 9   Reviews_d       4277 non-null   float64
 10  price_drop      4277 non-null   float64
 11  Mileages_d      4277 non-null   float64
 12  group           4277 non-null   float64
 13  test            4277 non-null   object 
 14  year            4277 non-null   int32  
 15  Manufacture     4277 non-null   object 
 16  model_name      4277 non-null   object 
dtypes: float64(7), int32(1), object(9

In [33]:
df.sample(10)

Car Names    Mileages  Ratings          Reviews  \
1722         2017 Dodge Charger SXT  17,688 mi.      4.4     (30 reviews)   
1043         2013 Honda Accord EX-L  76,284 mi.      4.8  (2,127 reviews)   
1902          2019 BMW X7 xDrive40i  16,475 mi.      4.7  (9,382 reviews)   
3968          2019 BMW X5 xDrive40i  49,310 mi.      4.7  (4,183 reviews)   
2618      2019 Audi Q5 Premium Plus  31,696 mi.      4.8    (906 reviews)   
2813       2021 GMC Yukon XL Denali  84,754 mi.      3.3     (33 reviews)   
3003       2021 Chevrolet Malibu LT  40,848 mi.      4.6    (897 reviews)   
3599        2019 Mazda CX-5 Touring  15,988 mi.      4.7  (1,139 reviews)   
368           2021 BMW 330 i xDrive  35,662 mi.      4.5    (227 reviews)   
3237  2014 Mazda CX-5 Grand Touring  21,503 mi.      4.5     (26 reviews)   

     used/certified         price drop    Price  Price_d  used  Reviews_d  \
1722           Used    $750 price drop  $22,999  22999.0   1.0       30.0   
1043           Used  $1,392 price drop  $16,995  16995.0   1.0     2127.0   
1902  BMW Certified  $1,500 price drop  $65,082  65082.0   0.0     9382.0   
3968           Used    $172 price drop  $51,995  51995.0   1.0     4183.0   
2618           Used    $730 price drop  $42,109  42109.0   1.0      906.0   
2813           Used    $498 price drop  $86,000  86000.0   1.0       33.0   
3003           Used  $1,302 price drop  $22,995  22995.0   1.0      897.0   
3599           Used  $1,505 price drop  $24,891  24891.0   1.0     1139.0   
368            Used    $799 price drop  $43,758  43758.0   1.0      227.0   
3237           Used    $900 price drop  $13,491  13491.0   1.0       26.0   

      price_drop  Mileages_d   group                                 test  \
1722       750.0     17688.0   376.0          [2017, Dodge, Charger, SXT]   
1043      1392.0     76284.0   105.0          [2013, Honda, Accord, EX-L]   
1902      1500.0     16475.0   760.0           [2019, BMW, X7, xDrive40i]   
3968       172.0     49310.0   757.0           [2019, BMW, X5, xDrive40i]   
2618       730.0     31696.0   721.0      [2019, Audi, Q5, Premium, Plus]   
2813       498.0     84754.0  1502.0       [2021, GMC, Yukon, XL, Denali]   
3003      1302.0     40848.0  1458.0        [2021, Chevrolet, Malibu, LT]   
3599      1505.0     15988.0   948.0         [2019, Mazda, CX-5, Touring]   
368        799.0     35662.0  1430.0          [2021, BMW, 330, i, xDrive]   
3237       900.0     21503.0   147.0  [2014, Mazda, CX-5, Grand, Touring]   

      year Manufacture              model_name  
1722  2017       Dodge          [Charger, SXT]  
1043  2013       Honda          [Accord, EX-L]  
1902  2019         BMW         [X7, xDrive40i]  
3968  2019         BMW         [X5, xDrive40i]  
2618  2019        Audi     [Q5, Premium, Plus]  
2813  2021         GMC     [Yukon, XL, Denali]  
3003  2021   Chevrolet            [Malibu, LT]  
3599  2019       Mazda         [CX-5, Touring]  
368   2021         BMW        [330, i, xDrive]  
3237  2014       Mazda  [CX-5, Grand, Touring]

In [34]:
df.describe()

Ratings        Price_d         used     Reviews_d    price_drop  \
count  4277.000000    4277.000000  4277.000000   4277.000000   4277.000000   
mean      4.486720   41848.259995     0.836801   1134.119009   1152.564181   
std       0.466659   27049.022630     0.369590   1875.937754   1459.814278   
min       1.400000    3595.000000     0.000000      0.000000    100.000000   
25%       4.400000   29490.000000     1.000000    152.000000    491.000000   
50%       4.600000   36998.000000     1.000000    620.000000    890.000000   
75%       4.800000   47988.000000     1.000000   1372.000000   1368.000000   
max       5.000000  899000.000000     1.000000  27885.000000  40000.000000   

          Mileages_d        group         year  
count    4277.000000  4277.000000  4277.000000  
mean    35518.861585   969.390227  2018.917699  
std     25877.814371   438.265746     2.200807  
min       143.000000     0.000000  1997.000000  
25%     17279.000000   683.000000  2018.000000  
50%     28406.000000   962.000000  2019.000000  
75%     46609.000000  1332.000000  2020.000000  
max    277281.000000  1745.000000  2022.000000

In [52]:
df.to_csv('prepared_data1.csv')

### Numpy

In [35]:
import numpy as np

1. Вычислите A + B, A - B
 
 $\\
A = \left(
\begin{array}{cccc}
1 & -2 & 4\\
2 & 0 & -1\\
\end{array}
\right), B = \left(
\begin{array}{cccc}
5 & 2 & 3\\
4 & 6 & 2\\
\end{array}
\right)$

In [36]:
A = np.array([[1,-2,4],[2,0,-1]])
A

array([[ 1, -2,  4],
       [ 2,  0, -1]])

In [37]:
B = np.array([[5,2,3],[4,6,2]])
B

array([[5, 2, 3],
       [4, 6, 2]])

In [38]:
A+B

array([[6, 0, 7],
       [6, 6, 1]])

In [39]:
A-B

array([[-4, -4,  1],
       [-2, -6, -3]])

2. Найдите матрицу С = A - 3B
 
 $\\
A = \left(
\begin{array}{cccc}
1 & 2 \\
2 & -1\\
3 & 0\\
\end{array}
\right), B = \left(
\begin{array}{cccc}
-1 & 1 \\
1 & 2\\
0 & 0\\
\end{array}
\right)$

In [40]:
A = np.array([[1,2],[2,-1],[3,0]])
A

array([[ 1,  2],
       [ 2, -1],
       [ 3,  0]])

In [41]:
B = np.array([[-1,1],[1,2],[0,0]])
B

array([[-1,  1],
       [ 1,  2],
       [ 0,  0]])

In [42]:
C = A -3*B
C

array([[ 4, -1],
       [-1, -7],
       [ 3,  0]])

3. Вычислите С = AB
 
 $\\
A = \left(
\begin{array}{cccc}
1 & -1 \\
2 & 0\\
3 & 0\\
\end{array}
\right), B = \left(
\begin{array}{cccc}
1 & 1 \\
2 & 0\\
\end{array}
\right)$

In [43]:
A = np.array([[1,-1],[2,0],[3,0]])
A

array([[ 1, -1],
       [ 2,  0],
       [ 3,  0]])

In [44]:
B = np.array([[1,1],[2,0]])
B

array([[1, 1],
       [2, 0]])

In [45]:
C=A.dot(B)
C

array([[-1,  1],
       [ 2,  2],
       [ 3,  3]])

4. Вычислите определитель матрицы А
 
 $\\
A = \left(
\begin{array}{cccc}
6 & -1 & 4\\
2 & 1 & 10\\
8 & 0 & 2\\
\end{array}
\right)$

In [46]:
A = np.array([[6,-1,4],[2,1,10],[8,0,2]])
A

array([[ 6, -1,  4],
       [ 2,  1, 10],
       [ 8,  0,  2]])

In [47]:
np.linalg.det(A)

-95.99999999999999

5. Вычислите матрицу, обратную матрице А. И покажите, что она действительно является обратной
 
 $\\
A = \left(
\begin{array}{cccc}
3 & 3 & -1\\
4 & 1 & 3\\
1 & -2 & -2\\
\end{array}
\right)$

In [48]:
A = np.array([[3,3,-1],[4,1,3],[1,-2,-2]])
A

array([[ 3,  3, -1],
       [ 4,  1,  3],
       [ 1, -2, -2]])

In [49]:
An = np.linalg.inv(A)
An

array([[ 0.07407407,  0.14814815,  0.18518519],
       [ 0.2037037 , -0.09259259, -0.24074074],
       [-0.16666667,  0.16666667, -0.16666667]])

In [50]:
C = A.dot(An)
C

array([[ 1.00000000e+00, -8.32667268e-17,  2.77555756e-17],
       [ 2.77555756e-17,  1.00000000e+00,  2.77555756e-17],
       [-5.55111512e-17,  5.55111512e-17,  1.00000000e+00]])

In [51]:
# можно считать, что на главной диагонали стят 1, а остлаьные элементы 0